export * from './types';
export * from './LogoIcon';

// Re-export Lucide icons with clean, standardized, semantic names
export {
  // Shell & Window Controls
  PanelLeft as PanelLeftIcon,
  PanelLeftClose as PanelLeftCloseIcon,
  Minus as MinimizeIcon,
  Square as MaximizeIcon,
  Copy as RestoreIcon,
  X as CloseIcon,

  // Navigation & Core Views
  Home as HomeIcon,
  LayoutDashboard as DashboardIcon,
  Layers as LayersIcon,
  Users as UsersIcon,
  Settings as SettingsIcon,
  HelpCircle as HelpIcon,
  Code2 as CodeIcon,
  Terminal as TerminalIcon,
  Sparkles as SparklesIcon,
  Compass as CompassIcon,

  // Developer Workspace & Directories
  Box as BoxIcon,
  Folder as FolderIcon,
  FolderTree as FolderTreeIcon,
  Sliders as SlidersIcon,
  Database as DatabaseIcon,
  Layout as LayoutIcon,
  AppWindow as AppWindowIcon,
  Zap as ZapIcon,
  Link as LinkIcon,
  Cpu as CpuIcon,
  Image as ImageIcon,
  Monitor as MonitorIcon,

  // Theme, Typography & Appearance
  Sun as SunIcon,
  Moon as MoonIcon,
  Laptop as SystemIcon,
  Palette as PaletteIcon,
  Type as TypeIcon,
  ZoomIn as ZoomInIcon,

  // Actions, Inputs, Docs & Utilities
  ChevronDown as ChevronDownIcon,
  Pencil as EditIcon,
  Keyboard as KeyboardIcon,
  RefreshCw as RefreshIcon,
  Check as CheckIcon,
  CheckCircle2 as CheckCircleIcon,
  Plus as PlusIcon,
  Command as CommandIcon,
  Mail as MailIcon,
  Shield as ShieldIcon,
  ShieldCheck as ShieldCheckIcon,
  FileText as FileTextIcon,
  Info as InfoIcon,
  AlertCircle as AlertCircleIcon,
  AlertTriangle as AlertTriangleIcon,
  ExternalLink as ExternalLinkIcon,
  BookOpen as BookOpenIcon,
  Eye as EyeIcon,
  Search as SearchIcon,

  // Local Mesh navigation
  Workflow as WorkflowIcon,
  Package as PackageIcon,
  ScrollText as ScrollTextIcon,

  // Models, Logs & Settings views
  Download as DownloadIcon,
  Trash2 as TrashIcon,
  FolderOpen as FolderOpenIcon,
  HardDrive as HardDriveIcon,
  Play as PlayIcon,
  Square as StopIcon,
  Copy as CopyIcon,
  ClipboardCopy as ClipboardCopyIcon,
  Gauge as GaugeIcon,
  ArrowDownToLine as JumpToBottomIcon,
  Wrench as WrenchIcon,
  XCircle as XCircleIcon,
  LoaderCircle as LoaderIcon,
  MemoryStick as MemoryIcon,
  Ban as CancelIcon,
  Eraser as EraserIcon,
  Unplug as UnplugIcon,

  // Pipelines view
  Maximize2 as FitViewIcon,
  Dices as DiceIcon,
  ChevronRight as ChevronRightIcon,

  // Generate view (viewer toolbar, dock)
  PanelRight as PanelRightIcon,
  PanelRightClose as PanelRightCloseIcon,
  Focus as FocusIcon,
  Grid3x3 as GridIcon,
  Pyramid as WireframeIcon,
  Rotate3d as AutoRotateIcon,
  ImagePlus as ImagePlusIcon,
  Cuboid as MeshIcon,
  Power as PowerIcon,
  Shrink as ReduceIcon,
  Waves as SmoothIcon,
  Scissors as FloatersIcon,
  Wand2 as CleanIcon,
  PaintBucket as FillHolesIcon,
  ArrowUpFromDot as NormalsIcon,
  Undo2 as UndoIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  Timer as TimerIcon,
  Camera as CameraIcon,
  GripVertical as GripVerticalIcon,
} from 'lucide-react';
